### ISSUE TITLE
Add an option to set both home screen and lock screen

### ISSUE THREAD

**Issue by timekone** [AdityaMulgundkar/wallpaper_manager#11]
It would be useful to have a constant like `WallpaperManager.BOTH`, so we could set both lock screen and home screen in one method call.
I think this may also be a workaround for #6.

**Comment by AdityaMulgundkar** [comment]
@timekone Hey! I have just pushed an update for v1.0.8 (@ApoorvaAditya here as implemented in his PR). It would be great if you can check if #6 is solved by the update or not.  (Since I cannot). Thank you in advance.
