### ISSUE TITLE
Set Lock Screen Wallpaper not working in Redmi Note 8

### ISSUE THREAD

**Issue by praonde** [AdityaMulgundkar/wallpaper_manager#18]
Some users with **Redmi Note 8** in my app are reporting this kind of error (set lock screen not working) , only happens in **Lock Screen** and only with this smartphone, with other phones are okay. Home Screen also are okay.

**Comment by codingstark-dev** [comment]
Same issue!!

> Some users with **Redmi Note 8** in my app are reporting this kind of error (set lock screen not working) , only happens in **Lock Screen** and only with this smartphone, with other phones are okay. Home Screen also are okay.

**Comment by AdityaMulgundkar** [comment]
@praonde @refoxdev Please go through the readme before creating new issues.

> Xiaomi/MIUI does not support changing Lock Screen Wallpapers directly from the Android API (Source). You might want to look at creating a Lock Screen Launcher app instead.

**Comment by codingstark-dev** [comment]
Sorry bro I forget! @AdityaMulgundkar
