### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by csedeepakyadav** [AdityaMulgundkar/wallpaper_manager#4]
![s](https://user-images.githubusercontent.com/22419021/79058568-51090500-7c8d-11ea-908e-1c349d88353e.png)

**Comment by AdityaMulgundkar** [comment]
Hi @csedeepakyadav. It seems like your setup/project is not configured to AndroidX, here's how you can check that and try to solve (https://stackoverflow.com/questions/56489549/flutter-getting-build-error-on-image-picker-0-6-09/56490440#56490440).

In case you have migrated the project to AndroidX & are still facing the same issue with your build, please reply back to me here with some more data. I'm going to need the following:

- `flutter doctor -v`
- `flutter build --verbose`
- some minimal code sample to reproduce the issue

Thank you

**Comment by csedeepakyadav** [comment]
Thank you for your quick response.

- App is configured to AndroidX.

- I tried all possible solutions and finally 
I managed to resolve the issue by copying  'res' folder of the app to
 'B:\flutter\.pub-cache\hosted\pub.dartlang.org\wallpaper_manager-1.0.6\android\src\main'
which just doubled the size of apk but it's working now.

For MIUI phones Wallpaper for LockScreen not working, please make it work if possible. (You have mentioned it earlier).



![Screenshot (159)](https://user-images.githubusercontent.com/22419021/79076304-a2a9a200-7d16-11ea-8880-4122b646bf53.png)

Again I would like to thank you for such a great plugin.

**Comment by AdityaMulgundkar** [comment]
Thanks a lot for providing a fix for the issue @csedeepakyadav yourself. Two things to mention before I close this issue off:

- You should try to document the exact steps on how to reproduce any issue in general, next time onwards. For now, I'll look into the 'res' folder - good catch, maybe I have missed something over there. This issue hasn't come up for anyone else, but I'll still take a deeper look into it soon.
- For the MI UI issue, I have figured out a solution, but couldn't take out the time to fix it. I'll do that this week I guess. The solution is this - If the device is MI-based & the lock screen function is called, save the image to the user's device first, and then use the `image_picker` library (or something similar) to pick that image out of the gallery & then select the "set as wallpaper" option. The user will have to manually select the image (after the gallery opens) and the set wallpaper option from the gallery with this method, though.

If in case I come up with a better MI UI fix, or if I just implement the above in one of the future versions of the library, I'll make sure to message you here!

Thank you
