### ISSUE TITLE
No effect when I set the LOCK_SCREEN status

### ISSUE THREAD

**Issue by zhoutongbie** [AdityaMulgundkar/wallpaper_manager#5]
version ：android 8.1.0

No effect when I set the LOCK_SCREEN status

why?

    try {
      result = await WallpaperManager.setWallpaperFromAsset(
          assetPath, WallpaperManager.LOCK_SCREEN);
    } on PlatformException {
      result = 'Failed to get wallpaper.';
    }

**Comment by AdityaMulgundkar** [comment]
Hi @zhoutongbie, MI UI does not allow you to set a Lock Screen wallpaper, as mentioned here: https://in.c.mi.com/thread-1252992-1-0.html

This is a known issue for MI phones & I'm looking at possible solutions right now. If I find a fix for it I'll update you here.

In case you're facing this issue on some other device (other than MI), please provide more details such as:

- log of your `flutter doctor`
- way/ steps to reproduce the error
- what version of the wallpaper_manager plug-in are you using, in your pubspec.yaml?

**Comment by codingstark-dev** [comment]
same issue facing! I am also using Xiaomi device.
