### ISSUE TITLE
Android resource linking failed

### ISSUE THREAD

**Issue by MuhammadAkkad** [AdityaMulgundkar/wallpaper_manager#7]
Hello 
im having this error on release mode only
it doesnt show on debug,run or profile.
im also able to build App bundle successfully.
i also tried building without this line: `android:theme="@style/LaunchTheme"` 

Execution failed for task ':wallpaper_manager:verifyReleaseResources'.

> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade

   > 1 exception was raised by workers:

     com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed

     C:\src\sdk\flutter\.pub-cache\hosted\pub.dartlang.org\wallpaper_manager-1.0.6\android\src\main\AndroidManifest.xml:7:9-12:15: AAPT: error: resource style/LaunchTheme (aka com.mulgundkar.wallpaper_manager:style/LaunchTheme) not found.

`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="111111111111111111111">
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="ANDROID.PERMISSION.READ_EXTERNAL_STORAGE"/>

    
    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="1111111111"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
          android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>

        <meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="111111111111111111111111111111"/>
        
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />

    </application>
</manifest>`

this is the files its looking for i think?
`<?xml version="1.0" encoding="utf-8"?>
<resources>
    <style name="LaunchTheme" parent="@android:style/Theme.Black.NoTitleBar">
        
        <item name="android:windowBackground">@drawable/launch_background</item>
    </style>
</resources>
`

Flutter doctor
`[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.18363.535], locale en-US)
    • Flutter version 1.12.13+hotfix.9 at C:\src\sdk\flutter
    • Framework revision f139b11009 (4 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:/Users/09370755/AppData/Local/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:/Users/09370755/AppData/Local/Android/Sdk
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3.3
    • Flutter plugin version 45.1.2
    • Dart plugin version 193.6911.31

[√] Connected device (1 available)
    • SM N960F • 26715611da1c7ece • android-arm64 • Android 10 (API 29)

• No issues found!
Process finished with exit code 0`

**Comment by AdityaMulgundkar** [comment]
Hi @MuhammadAkkad. This issue was pointed out previously, but without much relevant data, I wasn't able to narrow it down. Thanks a lot for providing the exact steps. I was able to replicate the issue on my end & I have fixed it now. This seems to be a common issue with AAPT builds; which is unfortunately not well documented.

Anyways, you should update the plug-in to `v1.0.7` and test building again. Hopefully, the error is gone now; so I'm closing this issue. Have a good day!

**Comment by MuhammadAkkad** [comment]
thanks, problem solved.
